# Generated by Django 2.2.24 on 2023-01-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '8770_bulk_index_queue_insert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maplayer',
            options={'default_permissions': (), 'managed': True, 'permissions': (('no_access_to_maplayer', 'No access to map layer'),)},
        ),
    ]
